<div class="row-fluid">
    <div class="span5">
        <legend>Assistência Técnica</legend>
        <h4>Garantia (Política de Garantia e SAC)</h4>
        <h5>A garantia é para defeitos de fábrica</h5>
        <p>Quando um produto apresentar defeito, o consumidor deverá entrar em contato com o SAC da marca/fábrica para ser direcionado a uma Assistência Técnica Autorizada. Ficará a critério do cliente de ir até a loja onde adquiriu o produto, embora isto poderá gerar um tempo maior para a solução do problema. A Assistência Autorizada verificará o problema e diagnosticará se este é de fabricação ou não.</p>
        <h5>Sendo defeito de fabricação</h5>
        <p>A Assistência Técnica fará o conserto de qualquer peça. Caso este reparo seja inviável, e o produto estiver na garantia, o mesmo será substituído.</p>
        <h5>Não sendo defeito de fabricação</h5>
        <p>A Assistência Técnica providencia um orçamento do conserto e entra em contato com o cliente, se este estiver de acordo, o reparo será realizado, se em desacordo o produto é devolvido ao cliente sem nenhuma alteração.
    </div>
    <div class="span6">
        <legend>Dúvidas Frequentes</legend>

        <h5>O QUE É DEFEITO DE FÁBRICA:</h5>
        <p>
            1. Costuras – Pontos sem costura, desfiando ou rente à ponta do tecido;
            <br />
            2. Montagem (Rebites) – soltos, tortos, mal colocados ou a falta de rebites;
            <br />
            3. Falta de componentes/Acessórios – Alça tira colo, alça carona, alça rígida, cursores, puxadores do cursor, logotipo, carrinhos, pés de apoio;
            <br />
            4. Defeitos detectados antes da utilização – Cadeados, fechos, zíperes, carrinhos, mosquetões.
        </p>
        <br />
        <h5>O QUE NÃO COBRE A GARANTIA:</h5>
        <p>
            1. Ausência de defeito;
            <br />
            2. Indícios de uso inadequado;
            <br />
            3. Indícios de dano acidental;
            <br />
            4. Desgaste natural em decorrência do uso;
            <br />
            5. Lavagem inadequada do produto.
            <br />
            6. Ponto de costura arrebentado.
            <br />
            7. Ralados.
            <br />
            8. Rasgos.
        </p>
    </div>
</div>