<form method="post">
    Senha<input type="text" name="senha_pessoa">
    Email<input type="text" name="email_pessoa">
    Nome<input type="text" name="nome_pessoa">
    Tel<input type="text" name="tel_res_pessoa">
    Cel<input type="text" name="tel_cel_pessoa">
    Tipo Acesso<input type="text" name="tx_tipo_acesso">
    Endereco<input type="text" name="endereco_pessoa">
    Ponto<input type="text" name="ponto_ref_pessoa">
    <input type="submit" value="Enviar">
</form>

