<div id="myCarousel" class="carousel slide">
    <br />
    <div class="carousel-inner">
        <div class="active item">
            <div class="span4 offset1">
                <h4>Conheça a empresa</h4>
                A SOS Malas é uma empresa especializada no conserto e assistência técnica de malas. Além disso restauramos malas de todas as marcas e modelos.
                <p>
                    <br />
                    <a class="btn btn-large" href="<?php echo $this->url(array('controller' => 'artigos', 'action' => 'index', 'id' => 3)) ?>">Leia mais</a>
                </p>
            </div>
            <div class="span4 offset1">
                <img height="300" src="/media/banner/sobre.png">
            </div>
        </div>
        <div class="item">
            <div class="span4 offset1">
                <h4>Delivery</h4>
                Pensando na comodidade e bem estar dos nossos clientes, a SOS Malas oferece como cortesia o serviço de coleta e entrega, apenas no Distrito Federal, do produto em sua residência (Delivery).
                <p>
                    <br />
                    <a class="btn btn-large" href="<?php echo $this->url(array('controller' => 'artigos', 'action' => 'index', 'id' => 4)) ?>">Leia mais</a>
                </p>
            </div>
            <div class="span4 offset1">
                <img height="300" src="/media/banner/slide1.png">
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div id="box2" class="row-fluid">
    <ul class="thumbnails span12">
        <h4><i class="icon-share"></i> Conheça alguns de nossos clientes</h4>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/aireuropa.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.aireuropa.com.br">www.aireuropa.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/taca.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.taca.com.br">www.taca.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/passaredo.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.passaredo.com.br">www.passaredo.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/delta.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.delta.com.br">www.delta.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/azul.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.azul.com.br">www.azul.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/trip.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.trip.com.br">www.trip.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/tam.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.tam.com.br">www.tam.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/copa-airlines.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.copaairlines.com.br">www.copaairlines.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/aerolineas.png">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.aerolineas.com.br">www.aerolineas.com.br</a>
            </p>
        </li>
        <li class="thumbnail span2">
            <img height="80" width="100" class="img-polaroid" src="/media/avatar/american-airlines.jpg">
            <p align="center">
                Conheça mais acessando <br /><a href="http://www.americanairlines.com.br">www.americanairlines.com.br</a>
            </p>
        </li>
    </ul>
</div>
<div id="box3" class="row-fluid">
    <h4><i class="icon-share"></i> Noticias</h4>
    <p class="span12">
        <i class="icon-comment"></i> <i>Caro cliente você tambem pode acompanhar o andamento do seu processo atráves do sistema.</i> 
        <a href="<?php echo $this->url(array('controller' => 'artigos', 'action' => 'index', 'id' => 5)) ?>">Saiba mais</a>
    </p>
    <p class="span12">
        <i class="icon-comment"></i> <i>Você sabia que a SOS Malas vai buscar e devolver o seu produto em sua casa?</i> 
        <a href="<?php echo $this->url(array('controller' => 'artigos', 'action' => 'index', 'id' => 1)) ?>">Saiba mais</a>
    </p>
    <p class="span12">
        <i class="icon-comment"></i> <i>Você sabia que a SOS Malas concertou 3270 malas neste ano?</i> 
        <a href="<?php echo $this->url(array('controller' => 'artigos', 'action' => 'index', 'id' => 2)) ?>">Saiba mais</a>
    </p>
</div>