<style type="text/css">
    .thumbnail {
        height: 370px;
    }
    .img-polaroid {
        max-height: 65px;
        max-width: 95%;
        margin-bottom: 10px;
    }
</style>
<div class="">
    <h3>Parceiros</h3>
    <ul class="thumbnails span12">
        <li class="span1">
        <center><h5>Benelton</h5></center>
        <img class="img-polaroid" src="/media/avatar/benelton.png">
        </li>
        <li class="span1">
        <center><h5>Eminent</h5></center>
        <img class="img-polaroid" src="/media/avatar/cruzeiro-eminent.png">
        </li>
        <li class="span1">
        <center><h5>Sestini</h5></center>
        <img class="img-polaroid" src="/media/avatar/sestini-monster.png">
        </li>
        <li class="span1">
        <center><h5>Sestini</h5></center>
        <img class="img-polaroid" src="/media/avatar/sestini-speeda.png">
        </li>
        <li class="span1">
        <center><h5>Luxcel</h5></center>
        <img class="img-polaroid" src="/media/avatar/luxcel-poloking.jpg">
        </li>
        <li class="span1">
        <center><h5>Pacific</h5></center>
        <img class="img-polaroid" src="/media/avatar/pacific.png">
        </li>
        <li class="span1">
        <center><h5>Cruzeiro</h5></center>
        <img class="img-polaroid" src="/media/avatar/cruzeiro-sportbag.png">
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="sestini" class="thumbnail span3">
        <center><h3>Sestini</h3></center>
        <img class="img-polaroid" src="/media/avatar/sestini2.png">
        <p style="text-align: justify;">
            Uma empresa nacional fundada em 1994 que surgiu com a abertura das importações no mercado brasileiro, e foi um agente importante na transformação deste segmento, trazendo produtos inovadores com preços acessíveis. Investimos muito em qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.sestini.com.br">www.sestini.com.br</a></p>
        </li>

        <li id="adventeam" class="thumbnail span3">
        <center><h3>ADVenTeam</h3></center>
        <img class="img-polaroid" src="/media/avatar/adventeam.png">
        <p style="text-align: justify;">
            A LUXCEL é um dos principais players do país na comercialização da mais completa linha de acessórios como malas, mochilas, pastas , frasqueiras, carteiras , cintos e bolsas femininas com marcas próprias e licenciadas.
        </p>
        <p><strong>Site:</strong> <a href="http://luxcel.com.br">www.luxcel.com.br</a> </p>
        </li>

        <li id="yes" class="thumbnail span3">
        <center><h3>Yes</h3></center>
        <img class="img-polaroid" src="/media/avatar/yes.png">
        <p style="text-align: justify;">
            Há mais de 30 anos a YES é reconhecida mundialmente pela qualidade e variedade de seus produtos. No Brasil consolida sua marca e conquista posições de destaque no mercado brasileiro há mais de 20 anos.
        </p>
        <p><strong>Site:</strong> <a href="http://www.yesbrasil.com.br">www.yesbrasil.com.br</a></p>
        </li>
        <li id="batiki" class="thumbnail span3">
        <center><h3>Batiki</h3></center>
        <img class="img-polaroid" src="/media/avatar/batiki.png">
        <p style="text-align: justify;">
            A Batiki oferece, há mais de 20 anos, qualidade, inovação e uma completa linha de soluções para o dia a dia, tanto familiar quanto profissional. O departamento de compras especializado está em constante procura, sempre atrás de tendências, produtos de qualidade e que sejam inovadores para o dia a dia de todos os brasileiros. 
        </p>
        <p><strong>Site:</strong> <a href="http://www.batiki.com.br">www.batiki.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="benelton" class="thumbnail span3">
        <center><h3>Bagaggio</h3></center>
        <img class="img-polaroid" src="/media/avatar/bagaggio.png">
        <p style="text-align: justify;">
            A BAGAGGIO é uma empresa familiar que atua no comércio de malas, bolsas, pastas, carteiras e acessórios para viagem, desde 1942. Está em constante expansão, e possui o site de e-commerce que é uma opção cômoda para o consumidor que busca praticidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.bagaggio.com.br/">http://www.bagaggio.com.br/</a></p>
        </li>

        <li id="delsey" class="thumbnail span3">
        <center><h3>Delsey</h3></center>
        <img class="img-polaroid" src="/media/avatar/delsey.png">
        <p style="text-align: justify;">
            Líder em design e inovação, DELSEY é uma marca francesa icônica que produz malas e acessórios de viagem desde 1946. Uma mala DELSEY é vendida a cada 10 segundos ao redor do mundo, descubra o nosso universo. 
        </p>
        <p><strong>Site:</strong> <a href="http://www.delsey.com.br">www.delsey.com.br</a></p>
        </li>
        <li id="cruzeiro" class="thumbnail span3">
        <center><h3>Cruzeiro</h3></center>
        <img class="img-polaroid" src="/media/avatar/cruzeiro.jpg">
        <p style="text-align: justify;">
            Os conceitos de globalização e qualidade que hoje se impõe são fatores determinantes para a sobrevivencia empresarial em um mercado forte, exigente e competitivo. Pensando nisto, integramos estes conceitos à filosofia de crescimento da Cruzeiro. 
        </p>
        <p><strong>Site:</strong> <a href="http://www.malascruzeiro.com.br">http://www.malascruzeiro.com.br</a></p>
        </li>
        <li id="zapp" class="thumbnail span3">
        <center><h3>Zapp</h3></center>
        <img class="img-polaroid" src="/media/avatar/zapp.png">
        <p style="text-align: justify;">
            A missão da Zapp é atender com presteza e atenção aos clientes. Levando uma grande variedade de produtos e das melhores marcas. Uma empresa com o olhar no cliente onde a satisfação está em primeiro lugar!
        </p>
        <p><strong>Site:</strong> <a href="http://www.papelariazapp.com.br">http://www.papelariazapp.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="diplomata" class="thumbnail span3">
        <center><h3>Diplomata</h3></center>
        <img class="img-polaroid" src="/media/avatar/diplomata.png">
        <p style="text-align: justify;">
            Fundada em 1990, a Diplomata constitui-se hoje uma empresa solidamente estabelecida no mercado, cujo caráter profissional convive em perfeita harmonia com a familiaridade que une seus sócios, funcionários e colaboradores.
        </p>
        <p><strong>Site:</strong> <a href="http://malasdiplomata.com.br">http://malasdiplomata.com.br</a></p>
        </li>
        <li id="dermiwil" class="thumbnail span3">
        <center><h3>Dermiwil</h3></center>
        <img class="img-polaroid" src="/media/avatar/dermiwil.png">
        <p style="text-align: justify;">
            Logo no início de sua história, agregou artigos de Puericultura Leve, e hoje é um dos maiores fabricantes deste setor, com sua marca própria Baby Go e personagens mundialmente conhecidos que são aplicados em mamadeiras, chupetas, pratos, copos e demais acessórios para bebês.
        </p>
        <p><strong>Site:</strong> <a href="http://www.dermiwil.com.br">http://www.dermiwil.com.br</a></p>
        </li>
        <li id="fico" class="thumbnail span3">
        <center><h3>Fico</h3></center>
        <img class="img-polaroid" src="/media/avatar/fico.png">
        <p style="text-align: justify;">
            No meio do surf, há quem diga que a vida de um surfista daria um livro. E foi exatamente isso que aconteceu. Mais do que histórias de surf trips, Raphael Levy, o Fico, em depoimento ao jornalista e tradutor André Viana, conta a sua trajetória de lutas e vitórias.
        </p>
        <p><strong>Site:</strong> <a href="http://www.fico.com.br">http://www.fico.com.br</a></p>
        </li>
        <li id="fico" class="thumbnail span3">
        <center><h3>Holly</h3></center>
        <img class="img-polaroid" src="/media/avatar/holly.png">
        <p style="text-align: justify;">
            A Holly Classic, marca de mochilas, bolsas e malas de viagem não para. Com nove anos de mercado, a empresa se tornou referência em qualidade, estilo e preços competitivos, sempre surpreende com suas novidades.A empresa conta com uma marca própria que leva linhas cheias de atitude.
        </p>
        <p><strong>Site:</strong> <a href="http://www.hollyclassic.com.br">http://www.hollyclassic.com.br/</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="holly" class="thumbnail span3">
        <center><h3>Ika Class</h3></center>
        <img class="img-polaroid" src="/media/avatar/ika.png">
        <p style="text-align: justify;">
            Ser livre e ir. Ser livre é vir. Ser livre é amar. Ser livre é viajar não apenas mundo afora, mais principalmente para dentro de nós mesmos. Este é exatamente o nosso propósito.
        </p>
        <p><strong>Site:</strong> <a href="http://www.ikaclass.com.br">http://www.ikaclass.com.br</a></p>
        </li>
        <li id="primicia" class="thumbnail span3">
        <center><h3>PRIMICIA</h3></center>
        <img class="img-polaroid" src="/media/avatar/primicia.png">
        <p style="text-align: justify;">
            A PRIMICIA é a empresa líder no segmento de artigos para viagem, vem atuando há mais de 60 anos no mercado, formada por capital 100% nacional, embora tenha nascido na Argentina, tendo como fundadores os irmãos Leon e David Kasitzky.
        </p>
        <p><strong>Site:</strong> <a href="http://www.primicia.com.br">http://www.primicia.com.br</a></p>
        </li>
        <li id="lansay" class="thumbnail span3">
        <center><h3>LANSAY</h3></center>
        <img class="img-polaroid" src="/media/avatar/lansay.jpg">
        <p style="text-align: justify;">
            Há onze anos no mercado, a ISRACO é uma empresa nacional, especializada na fabricação e comercialização de malas, artigos para viagem e mochilas. Proprietária das marcas LANSAY, no segmento  de viagem e FICO, no segmento de mochilas, possui um  know how de 50 anos,  trazido por seus fundadores, que já atuavam no setor.
        </p>
        <p><strong>Site:</strong> <a href="http://www.lansay.com.br">http://www.lansay.com.br</a></p>
        </li>
        <li id="lepostiche" class="thumbnail span3">
        <center><h3>Le Postiche</h3></center>
        <img class="img-polaroid" src="/media/avatar/lepostiche.jpg">
        <p style="text-align: justify;">
            Fundada em 1978, a Le Postiche é a maior rede de bolsas, malas e acessórios de viagens do país. Com mais de 30 anos de história, a marca conquistou um alto grau de fidelidade de seus clientes com uma proposta de variedade de produtos, qualidade e preços competitivos.
        </p>
        <p><strong>Site:</strong> <a href="http://www2.lepostiche.com.br">http://www2.lepostiche.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="luen" class="thumbnail span3">
        <center><h3>Luen</h3></center>
        <img class="img-polaroid" src="/media/avatar/luen.png">
        <p style="text-align: justify; font-size: 11px;">
            Malas de viagem, a trabalho ou a passeio, são muito mais do que simples objetos para acondicionar seus pertences, levam lembranças, histórias, expectativas e conquistas. A Luen pensando nisto, oferece ao público, malas em Policarbonato das mais variadas estampas e modelos da renomada marca HeysUSA. Fundada em 2010, a Luen importa e distribui com excelência em atendimento para todo território nacional.
        </p>
        <p><strong>Site:</strong> <a href="http://www.luenbrasil.com.br">http://www.luenbrasil.com.br</a></p>
        </li>
        <li id="luxcel" class="thumbnail span3">
        <center><h3>Luxcel</h3></center>
        <img class="img-polaroid" src="/media/avatar/luxcel.png">
        <p style="text-align: justify;">
            A LUXCEL é um dos principais players do país na comercialização da mais completa linha de acessórios como malas, mochilas, pastas , frasqueiras, carteiras , cintos e bolsas femininas com marcas próprias e licenciadas.
        </p>
        <p><strong>Site:</strong> <a href="http://www.luxcel.com.br">http://www.luxcel.com.br</a></p>
        </li>
        <li id="nycow" class="thumbnail span3">
        <center><h3>NYCOW</h3></center>
        <img class="img-polaroid" width="95%" src="/media/avatar/nycow.jpg">
        <p style="text-align: justify;">
            Em meados de 1985 tinha inicio a fabricação, na cidade de São Paulo, das primeiras mochilas escolares Nycow, que no decorrer do tempo vieram se firmando em todo o mercado nacional como sinônimo de qualidade, durabilidade e preço justo.
        </p>
        <p><strong>Site:</strong> <a href="http://www.nycow.com.br">http://www.nycow.com.br</a></p>
        </li>
        <li id="tonin" class="thumbnail span3">
        <center><h3>Tonin</h3></center>
        <img class="img-polaroid" src="/media/avatar/tonin.png">
        <p style="text-align: justify;">
            Fundada em 1982, em Farroupilha, no Rio Grande do Sul, a Tonin iniciou as suas atividades com a produção de carteiras em couro e conquistou em dez anos espaço entre os líderes de mercado neste setor.
        </p>
        <p><strong>Site:</strong> <a href="http://www.nycow.com.br">http://www.nycow.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="roncato" class="thumbnail span3">
        <center><h3>Roncato</h3></center>
        <img class="img-polaroid" width="95%" src="/media/avatar/roncato.png">
        <p style="text-align: justify;">
            Roncato, o maior Fabricante de Malas, carteiras e acessórios de viagem da Europa, agora no Brasil!
        </p>
        <p><strong>Site:</strong> <a href="http://www.roncatobrasil.com.br/">http://www.roncatobrasil.com.br/</a></p>
        </li>
        <li id="santino" class="thumbnail span3">
        <center><h3>Santino</h3></center>
        <img class="img-polaroid" src="/media/avatar/santino.jpg">
        <p style="text-align: justify;">
            No Brasil a Santino é uma referência em empresa distribuidora de bolsas femininas, linha de viagem (malas, sacolas, frasqueiras e nécessaires), linha executiva (pastas e mochilas para notebook), linha escolar (mochilas, mochilas com carrinho, lancheiras e estojos).
        </p>
        <p><strong>Site:</strong> <a href="http://www.santino.com.br">http://www.santino.com.br</a></p>
        </li>
        <li id="samsonite" class="thumbnail span3">
        <center><h3>Samsonite</h3></center>
        <img class="img-polaroid" src="/media/avatar/samsonite.jpg">
        <p style="text-align: justify;">
            Através da LojaSamsonite.com saberá sempre e em tempo real todas as novidades, promoções e iniciativas da marca, sempre que quiser e no conforto da sua casa ou escritório.
        </p>
        <p><strong>Site:</strong> <a href="http://www.samsonite.com.br">http://www.samsonite.com.br</a></p>
        </li>
        <li id="shoping-risk" class="thumbnail span3">
        <center><h3>Shoping Risk</h3></center>
        <img class="img-polaroid" src="/media/avatar/shoping-risk.png">
        <p style="text-align: justify; font-size: 11px;">
            Nascido em Arapuá, interior de Minas Gerais, Edésio da Silva Gontijo, fundador do Shopping Risk, se muda para Goiânia ainda jovem, na esperança de um futuro promissor. Em 1981, transfere-se para Brasília, onde se tornou divulgador de livros. Já em 1985, passa a trabalhar na papelaria Ritz e Brito. A partir daí, começa a juntar dinheiro e, em 1990, funda o grupo Risk, na Ceilândia, com o dinheiro arrecadado durante os cinco anos antecedentes.
        </p>
        <p><strong>Site:</strong> <a href="http://www.papelariarisk.com.br">http://www.papelariarisk.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="tilibra" class="thumbnail span3">
        <center><h3>Tilibra</h3></center>
        <img class="img-polaroid" src="/media/avatar/tilibra.jpg">
        <p style="text-align: justify; font-size: 11px;">
            A Tilibra, líder no segmento de papelaria, há mais de 80 anos escreve uma história de valor na cidade de Bauru, interior de São Paulo. Além da produção de Material Escolar e Produtos de Papelaria, a empresa também é destaque no mercado de agendas e de produtos inovadores para casa e escritório. Seus produtos podem ser encontrados nas mais diversas papelarias, supermercados, atacadistas e grandes varejistas do Brasil.
        </p>
        <p><strong>Site:</strong> <a href="http://www.tilibra.com.br">http://www.tilibra.com.br</a></p>
        </li>
    </ul>
</div>