<style type="text/css">
    .thumbnail {
        height: 400px;
    }
</style>
<div class="">
    <h3>Parceiros</h3>
    <ul class="thumbnails">
        <li id="sestini" class="thumbnail span3">
        <center><h3>Sestini</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/sestini2.png">
        <p style="text-align: justify;">
            Uma empresa nacional fundada em 1994 que surgiu com a abertura das importações no mercado brasileiro, e foi um agente importante na transformação deste segmento, trazendo produtos inovadores com preços acessíveis. Investimos muito em qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.sestini.com.br">www.sestini.com.br</a></p>
        </li>

        <li id="adventeam" class="thumbnail span3">
        <center><h3>ADVenTeam</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/adventeam.png">
        <p style="text-align: justify;">
            A LUXCEL é um dos principais players do país na comercialização da mais completa linha de acessórios como malas, mochilas, pastas , frasqueiras, carteiras , cintos e bolsas femininas com marcas próprias e licenciadas.
        </p>
        <p><strong>Site:</strong> <a href="http://luxcel.com.br">www.luxcel.com.br</a> </p>
        </li>

        <li id="yes" class="thumbnail span3">
        <center><h3>Yes</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/yes.png">
        <p style="text-align: justify;">
            Há mais de 30 anos a YES é reconhecida mundialmente pela qualidade e variedade de seus produtos. No Brasil consolida sua marca e conquista posições de destaque no mercado brasileiro há mais de 20 anos.
        </p>
        <p><strong>Site:</strong> <a href="http://www.yesbrasil.com.br">www.yesbrasil.com.br</a></p>
        </li>
        <li id="batiki" class="thumbnail span3">
        <center><h3>Batiki</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/batiki.png">
        <p style="text-align: justify;">
            A Batiki oferece, há mais de 20 anos, qualidade, inovação e uma completa linha de soluções para o dia a dia, tanto familiar quanto profissional. O departamento de compras especializado está em constante procura, sempre atrás de tendências, produtos de qualidade e que sejam inovadores para o dia a dia de todos os brasileiros. 
        </p>
        <p><strong>Site:</strong> <a href="http://www.batiki.com.br">www.batiki.com.br</a></p>
        </li>
    </ul>
    <ul class="thumbnails">
        <li id="benelton" class="thumbnail span3">
        <center><h3>Bagaggio</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/bagaggio.png">
        <p style="text-align: justify;">
            A BAGAGGIO é uma empresa familiar que atua no comércio de malas, bolsas, pastas, carteiras e acessórios para viagem, desde 1942. Está em constante expansão, e possui o site de e-commerce que é uma opção cômoda para o consumidor que busca praticidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.benelton.com.br">www.benelton.com.br</a></p>
        </li>

        <li id="delsey" class="thumbnail span3">
        <center><h3>Delsey</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/delsey.png">
        <p style="text-align: justify;">
            Líder em design e inovação, DELSEY é uma marca francesa icônica que produz malas e acessórios de viagem desde 1946. Uma mala DELSEY é vendida a cada 10 segundos ao redor do mundo, descubra o nosso universo. 
        </p>
        <p><strong>Site:</strong> <a href="http://www.delsey.com.br">www.delsey.com.br</a></p>
        </li>
    </ul>

</div>