<div class="">
    <h3>Parceiros [Modelo visualização 1]</h3>
    <ul class="thumbnails">
        <li id="sestini" class="thumbnail span4">
        <center><h3>Sestini</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/sestini.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.sestini.com.br">www.sestini.com.br</a></p>
        </li>
        <li id="adventeam" class="thumbnail span4">
        <center><h3>ADVenTeam</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/adventeam.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.adventeam.com.br">www.adventeam.com.br</a></p>
        </li>
        <li id="yes" class="thumbnail span4">
        <center><h3>Yes</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/yes.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.yes.com.br">www.yes.com.br</a></p>
        </li>
    </ul>
    <h3>Parceiros [Modelo visualização 1]</h3>
    <ul id="batiki" class="thumbnails">
        <li class="thumbnail span12">
        <center><h3>Batiki</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/batiki.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.batiki.com.br">www.batiki.com.br</a></p>
        </li>
    </ul>
    <ul id="benelton" class="thumbnails">
        <li class="thumbnail span12">
        <center><h3>Benelton</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/benelton.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.benelton.com.br">www.benelton.com.br</a></p>
        </li>
    </ul>
    <ul id="yes" class="thumbnails">
        <li class="thumbnail span12">
        <center><h3>Yes</h3></center>
        <img class="img-polaroid" width="100px" src="/media/avatar/delsey.png">
        <p style="text-align: justify;">
            Uma empresa conceituada no mercado de mochilas, sua principal meta e aplicar a qualidade em um mercado de produtos com duração defeituosa em muitas marcas, além da qualidade busca também dar aos seus clientes o menor preço e a mais alta qualidade.
        </p>
        <p><strong>Site:</strong> <a href="http://www.delsey.com.br">www.delsey.com.br</a></p>
        </li>
    </ul>
</div>