<div class="row-fluid">
    <div class="span5">
        <img src="/images/servicos.png" alt=""/>
    </div>
    <div class="span6">
        <h3>Serviços</h3>
        <ul>
            <li>Recuperação de malas, bolsas e mochilas de viagens, cases, carrinhos de bebê, maletas, pastas e valises.</li>
            <li>Conserto, troca, adaptação e confecção de alças, carrinhos Trip Roll, zíper, cursores de zíper, rodas, bases das rodas, forros, etc.</li>
            <li>Confecção de detalhes para apliques em tecidos e couros, lanternagens com pinturas em bagagens rígidas.</li>
            <li>Costuras em geral, logomarcas, fechos segredos, cintas de malas, travas, fechos Tic-Tac, mosquetões, ombreiras, cantoneiras, dobradiças, bases superiores e inferiores de carrinhos Trip Roll, pés de apoio laterais e inferiores fixos e com extensores, armação interna, fundos de madeira, rebites, vivos protetores de canto, entre outros.</li>
            <li>Restauração de malas de fibra e entrega com pintura original.</li>
        </ul>
    </div>
    <div class="span5">
        <h3>Diferencial</h3>
        <p style="text-align: justify;">Pensando na comodidade e bem estar dos nossos clientes, a SOS Malas oferece como cortesia o serviço de coleta e entrega do produto em sua residência (Delivery).
            Sendo assim, realizamos um orçamento prévio no ato da coleta e após aprovação damos sequência ao conserto e depois de pronto o produto é devolvido no endereço solicitado sem custo adicional.
        </p>
    </div>
    <div class="span6">
        <h3>Tabela de Preços</h3>
        <a href="/media/files/catalogo.pdf"><img src="/images/pdf.png" alt=""/> Download</a>
    </div>
</div>