<div class="row-fluid">
    <img class="span4" src="/images/sobre.png">
    <div class="span4">
        <h3>SOS Malas, um sonho de sucesso.</h3>
        Desde 1989 - Antes como Di Couros (conserto de Malas e Calçados), hoje a SOS Malas é uma oficina especializada em consertos de malas, pastas, maletas, cases, mochilas e sacolas de viagens. Escolhida pelas companhias aéreas como colaboradora, foi fundada pelo empresário Sergio Caldas; com sede própria, um Técnico Responsável e uma equipe de funcionários qualificados para o atendimento e os serviços de restauração das bagagens. A SOS Malas é reconhecida por prestar serviços autorizados de Assistência Técnica a mais de 20 anos para diversas fábricas, papelarias e lojas.
        Sergio Caldas - Técnico Responsável
    </div>
</div>
<div class="row-fluid">
    <h3>Missão</h3>
    Prestar serviços com eficiência, segurança, economia e sustentabilidade, através de soluções inovadoras em conserto de malas, sacolas, bolsas, mochilas e afins para atender as expectativas dos clientes, fornecedores e colaboradores.
</div>
<div class="row-fluid">
    <h3>Visão</h3>
    Ser referência pela excelência dos serviços prestados, tornando-se a maior e melhor empresa em assistência técnica de malas de Brasília
</div>
<div class="row-fluid">
    <h3>Valores</h3>
    Satisfação do cliente, principal motivo da existência do negócio.
    Ética nos negócios, com os clientes e fornecedores.
    Respeito às pessoas, à natureza, à vida, à diversidade.
    Transparência nas relações com as partes integrantes.
</div>