<div class="row-fluid">
    <legend>Responsabilidade Socioambiental</legend>
    <div class="span6">
        <iframe width="520" height="415" src="//www.youtube.com/embed/A-0n4W1_q2Y" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="span5" style="font-size: 16px;">
        <h4>Desejamos um mundo melhor para todos!</h4>
        <br />
        <p>
            Cada dia que passa o nosso mundo nos cobra mais trabalhos, mais atenção
            menos tempo para as nossas familias, menos atividades ao ar livre, vivendo
            em selvas de pedra, indiferenças sociais, mais a SOS Malas, assim como muitas
            pessoas luta por um mundo melhor com mais abraços e sorrisos, familias em paz
            igualdade social.
        </p>
        <p>
            E em um mundo onde a preocupação com o meio ambiente é cada dia mais crescente
            a SOS Malas também da importancia a preservação da vida em nosso planeta
            e contribui para que o meio ambiente seja preservado utilizando materiais
            e técnicas que sejam menos ofensivas e que preservem o meio ambiente que
            desejamos para os nossos filhos.
        </p>
        <p>
            Reservamos este video ao lado para que você também possa assistir e se concientizar
            do mundo em que vivemos e se juntar a nós e muitos outros pela causa de tornar o
            nosso mundo um lugar melhor para se viver.
        </p>
    </div>
</div>