<form action="" method="post" class="form-horizontal">
    <?php echo 'Mensagem: '.$this->texto ?>
    <div class="control-group">
        <label class="control-label" for="inputEmail">OS: </label>
        <div class="controls">
            <!--<input type="text" readonly name="id" value="<?php echo $this->id ?>"><br>-->
            <?php echo $this->form->os?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputEmail">Cliente: </label>
        <div class="controls">
            <!--<input type="text" name="nome" value="<?php echo $this->nome ?>"><br>-->
            <?php echo $this->form->cliente?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputEmail">Data do Pedido: </label>
        <div class="controls">
          <!-- <input type="text" name="email" value="<?php echo $this->email ?>"><br>-->
            <?php echo $this->form->data_pedido?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">Endereço: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->endereco?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">Ponto de referência: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->ponto_referencia?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">Telefone Fixo: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->fone_fixo?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">PCM: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->pcm?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">Previsão da coleta: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->previsao_coleta?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">tipo: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->tipo?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="inputPassword">Status: </label>
        <div class="controls">
          <!--<input type="password" name="senha" value="<?php echo $this->senha ?>">-->
            <?php echo $this->form->tipo?>
        </div>
    </div>

    <!-- FIM DOS CAMPOS-->
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Salvar</button>
        </div>
    </div>
</form>