<form action="" class="form-inline" method="post">
    <legend>Coleta >> Consulta</legend>
    <div class="control-group">
        Filtrar por OS: <input class="input-mini" name="os_coleta" type="text" size="35">
        <button class="btn" type="submit">Buscar</button>
    </div>
    <br>
    <table class="table table-striped table-bordered">
        <thead>
        <th>OS</th>
        <th>Cliente</th>
        <th>Data do Pedido</th>
        <th>PCM</th>
        <th>Previsão de Coleta</th>
        <th>Tipo</th>
        <th>Status</th>
        <th></th>
        </thead>
        <tbody>
            <?php foreach ($this->listColeta as $coleta): ?>
                <tr>
                    <td><?php echo $coleta->os_coleta ?></td>
                    <td><?php echo $coleta->cliente_email ?></td>
                    <td><?php echo SOSMalas_Date::dateToView($coleta->data_pedido_coleta) ?></td>
                    <td><?php echo $coleta->pcm_coleta ?></td>
                    <td><?php echo SOSMalas_Date::dateToView($coleta->previsao_coleta) ?></td>
                    <td><?php echo $coleta->tipo_coleta ?></td>
                    <td><?php echo $this->statusColeta[$coleta->status_coleta] ?></td>
                    <td>
                        <div class="btn-group">
                            <a class="btn" href="/admin/coleta/editar/os_coleta/<?php echo $coleta->os_coleta ?>"><i class="icon-edit"></i></a>
                            <a class="btn btn-danger" href="/admin/coleta/delete/os_coleta/<?php echo $coleta->os_coleta ?>"><i class="icon-trash icon-white"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>