<div class="row-fluid">
    <h3>Processos - Consultas de DPR's e/ou AHL's</h3>
    <ul class="thumbnails">
        <li class="thumbnail span4">
            <h3 align="center">Empresa</h3>
            <form method="POST" class="offset1 form-signin" action="/admin/auth/login">
                <p>Empresas podem acessar e visualizar como estão os processos diretamente ligados a própria empresa.</p>
                <label><strong>Email:</strong> </label>
                <input type="text" name="email">
                <br />
                <label><strong>Senha:</strong> </label>
                <input type="password" name="password">
                <br />
                <button class="btn btn-primary">Acessar</button>
            </form>
        </li>
        <li class="thumbnail span4">
            <h3 align="center">Parceiro</h3>
            <form method="POST" class="offset1 form-signin" action="/admin/auth/login">
                <p>Parceiros podem acessar e visualizar como estão os processos diretamente ligados a próprio parceiro.</p>
                <label><strong>Email:</strong> </label>
                <input type="text" name="email">
                <br />
                <label><strong>Senha:</strong> </label>
                <input type="password" name="password">
                <br />
                <button class="btn btn-primary">Acessar</button>
            </form>
        </li>
        <li class="thumbnail span4">
            <h3 align="center">Cliente</h3>
            <form method="post" action="<?php echo $this->url(array('controller'=>'processos', 'action' => 'consulta')) ?>" class="offset1 form-signin">
                <p>Clíentes podem acessar e visualizar o andamento dos processos diretamente informando apenas o numero do mesmo.</p>
                <label><strong>Codigo recebido por e-mail ou telefone:</strong> </label>
                <input class="span10" placeholder="Leve em conta maiusculas e minusculas" type="text" name="nu_processo">
                <br />
                <div class="row-fluid">
                    <button class="btn btn-primary">Acessar</button>
                    <a href="<?php echo $this->url(array('controller' => 'contato', 'action' => 'index')) ?>" class="btn btn-warning">Esqueci o Nº do processo</a>
                </div>
            </form>
        </li>
    </ul>
</div>