<div class="row-fluid">
    <h3>Contate-nos</h3>
    <form class="form-horizontal span6">
        <p>
            Através deste formulário você pode solicitar a sua coleta, ou retirar dúvidas relacionadas aos nossos serviços.
        </p>
        <br />
        <div class="control-group">
            <label class="control-label">Nome Completo: </label>
            <div class="controls">
                <input type="text" name="nome">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Email: </label>
            <div class="controls">
                <input type="email" name="email">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Telefone: </label>
            <div class="controls">
                <input type="email" name="email">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Mensagem: </label>
            <div class="controls">
                <textarea name="texto"></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Anexo: </label>
            <div class="controls">
                <input type="file" name="anexo">
            </div>
        </div>
        <div class="control-group">
            <label data-title="Setor" data-trigger="hover" data-content="Indique quais os setores que deseja contactar" class="control-label popover-element">
                <i class="icon-question-sign"></i>
                Setor: 
            </label>
            <div class="controls">
                <input class="checkbox" type="checkbox" name="setor"> Financeiro
                <input type="checkbox" name="setor"> Administrativo
                <input type="checkbox" name="setor"> Atendimento
                <input type="checkbox" name="setor"> Técnico
            </div>
        </div>
        <div class="control-group">
            <label data-title="Dicas" data-content="Marque se deseja receber retorno sobre o seu envio de contato" data-trigger="hover" class="control-label popover-element">
                <i class="icon-question-sign"></i> Desejo receber avisos: 
            </label>
            <div class="controls">
                <input class="checkbox" type="checkbox" name="receber"> Sim
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="button">Enviar</button>
        </div>
    </form>
    <div class="span5">
        <p>
            Através destes e-mails você poderá entrar em contato diretamento com cada um dos nossos setores.
        </p>
        <br />
        <p><strong><i class="icon-envelope"></i> Atendimento ao cliente:</strong> <a href="mailto:contato@sosmalas.com.br">contato@sosmalas.com.br</a></p>
        <p><strong><i class="icon-envelope"></i> Financeiro:</strong> <a href="mailto:financeiro@sosmalas.com.br">financeiro@sosmalas.com.br</a></p>
        <p><strong><i class="icon-envelope"></i> Administrativo:</strong> <a href="mailto:adelita@sosmalas.com.br">adelita@sosmalas.com.br</a></p>
        <p><strong><i class="icon-envelope"></i> Técnico Responsável:</strong> <a href="mailto:sergiocaldas@sosmalas.com.br">sergiocaldas@sosmalas.com.br</a></p>
    </div>
</div>