<!DOCTYPE html>
<html>
<head>
    <title>SOS Malas</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        setInterval(function () {
            window.location.reload();
        }, 3000);
    </script>
    <style type="text/css">
        div {
            /*border: 1px solid #000;*/
        }

        .topo-1 {
            background-image: url('/assets/img/background-site-1.png');
            background-repeat: repeat-x;
        }

        .menu-principal {
            margin: -6% 0 0 25%;
            border-radius: 5px;
            padding: 9px;
        }

        .menu-principal .nav {
            background-color: #fff;
            border-radius: 5px;
        }

        .menu-principal li {
            padding-right: 5px;
        }
    </style>
</head>
<body>
<div class="row">
    <div class="row-fluid">
        <div class="topo-1">
            <img src="/assets/img/background-site-2.png">
        </div>
        <div class="navbar menu-principal">
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li>
                        <a href="#"><i class="icon-home"></i> Menu</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-question-sign"></i> Sobre</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-th-large"></i> Serviços</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-cog"></i> Assistencia Técnica</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-user"></i> Parceiros</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-globe"></i> Sustentabilidade</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-list-alt"></i> Processos</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-envelope"></i> Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <h1>Content</h1>
    </div>
</div>
</body>
</html>