<fieldset>
    <legend>Área de Trabalho</legend>
    <ul class="thumbnails">
        <li class="span2" alt="Registro de Entradas">
            <div class="thumbnail">
                <center><h4>Pessoas</h4></center>
                <i class="icon-person"></i>
                <center>
                    <div class="btn-group-vertical">
                        <a href="/admin/pessoa/cadastro" class="btn btn-navbar">
                            <i class="icon-plus"></i>
                            Cadastrar
                        </a>
                        <a href="/admin/pessoa/pesquisar-pessoa" class="btn btn-navbar btn-info">
                            <i class="icon-search icon-white"></i>
                            Consultar
                        </a>
                    </div>
                </center>
            </div>
        </li>

<!--        <li class="span2" alt="Registro de Entradas">
            <div class="thumbnail">
                <center><h4>Entradas</h4></center>
                <i class="icon-paste-eng"></i>
                <center>
                    <div class="btn-group-vertical">
                        <a href="/admin/entrada/cadastro" class="btn">
                            <i class="icon-plus"></i>
                            Cadastrar
                        </a>
                        <a href="/admin/entrada/pesquisar-entrada" class="btn btn-navbar btn-info">
                            <i class="icon-search icon-white"></i>
                            Consultar
                        </a>
                    </div>
                </center>
            </div>
        </li>-->

<!--        <li class="span2" alt="">
            <div class="thumbnail">
                <center><h4>Coletas</h4></center>
                <i class="icon-package"></i>
                <center>
                    <div class="btn-group-vertical">
                        <a href="/admin/coleta/cadastro-coleta" class="btn btn-block">
                            <i class="icon-plus"></i>
                            Cadastrar
                        </a>
                        <a href="/admin/coleta/pesquisar-coleta" class="btn btn-navbar btn-info">
                            <i class="icon-search icon-white"></i>
                            Consultar
                        </a>
                    </div>
                </center>
            </div>
        </li>-->
        
        <li class="span2" alt="">
            <div class="thumbnail">
                <center><h4>Processos</h4></center>
                <i class="icon-package"></i>
                <center>
                    <div class="btn-group-vertical">
                        <a href="/admin/processos/cadastrar" class="btn btn-block">
                            <i class="icon-plus"></i>
                            Cadastrar
                        </a>
                        <a href="/admin/processos/pesquisar" class="btn btn-navbar btn-info">
                            <i class="icon-search icon-white"></i>
                            Consultar
                        </a>
                    </div>
                </center>
            </div>
        </li>

        <li class="span2">
            <div class="thumbnail">
                <i class="icon-logout" title="Sair do Sistema"></i>
                <a href="/admin/auth/logout">
                    <center><button class="btn btn-danger">Sair</button></center>
                </a>
            </div>
        </li>

    </ul>
</fieldset>
