<title>SOS Malas - Login <?php echo Zend_Registry::get('layoutTitle'); ?></title>
<meta charset="utf-8">
<link rel="stylesheet" href="/assets/css/bootstrap.css">
<link rel="stylesheet" href="/assets/css/bootstrap-min.css">
<style type="text/css">
    body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin input[type="text"],
    .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
    }
    .form-signin #email{
        background-position: left;
        padding: 7px 7px 7px 30px;
        background-repeat: no-repeat;
        background-image: url("/assets/img/usuario.png");
    }
    .form-signin #senha{
        background-position: left;
        padding: 7px 7px 7px 30px;
        background-repeat: no-repeat;
        background-image: url("/assets/img/chaves.png");
    }
</style>
<div class="container">
    <?php
        if ($this->msgSistema):
            ?>
            <div class="alert alert-danger"><?php echo $this->msgSistema ?></div>
            <?php
        endif;
        ?>
    <form class="form-signin" method="POST" action="">
        <center>
            <h4 class="form-signin-heading">SOS Malas - Painel Administrativo</h4>
        </center>
        <br>
        <p>Autenticar usuário</p>
        <hr>
        <?php
        if ($this->mensagem):
            ?>
            <div class="alert alert-danger"><?php echo $this->mensagem ?></div>
            <?php
        endif;
        ?>
        <div class="control-group">
            <label class="control-label"><b>Usuário:</b></label>
            <div class="controls">
                <input name="email" type="text" id="email" class="input-block-level" placeholder="Email">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label"><b>Senha:</b></label>
            <div class="controls">
                <input name="password" type="password" id="senha" class="input-block-level" placeholder="Senha">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn pull-right btn-primary" type="submit">Acessar</button>
                <br>
            </div>
        </div>
    </form>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <footer>
        <center>SOS Malas - Copyright©2013 SOS Malas - Todos os direitos reservados.</center>
    </footer>
</div>