<script type="text/javascript"><?php echo $this->js ?></script>
<?php echo $this->mensagem ?>
<style type="text/css">
    .form-horizontal{
        margin: 10% 0 20% 0;
    }
</style>
<form class="form-inline" method="post" action="/cliente/index/os">
    <h4>
        <center>Verifique como se encontra o estado do seu pedido de coleta</center>
    </h4>
    <br>
    <br>
    <br>
    <div class="control-group">
        <div class="controls">
            <label class="control-label">Insira o codigo da sua coleta e então clique em verificar: </label>
                <input type="text" name="hashcod" value="<?php echo $this->hashcod ?>" name="hashcod" class="input-small" placeholder="">
            <button class="btn btn-primary">Verificar</button>
        </div>
    </div>
    <br>
    <?php if (count($this->coleta)): ?>
        <table class="table table-bordered table-striped">
            <caption><h2>Resultado</h2></caption>
            <thead>
            <th>ID</th>
            <th>ORD/Serviço</th>
            <th>Coleta</th>
            <th>Entrega</th>
            <th>Mod./Marca</th>
            <th>Ref/Fábrica</th>
            <th>Status</th>
            <th>Previsão Entrega</th>
            <th>Observação</th>
            </thead>
            <tbody>
                <?php foreach ($this->coleta as $value): ?>
                    <tr>
                        <td><?php echo $value->id_processo ?></td>
                        <td><?php echo $value->os_processo ?></td>
                        <td><?php echo SOSMalas_Date::dateToView($value->data_coleta_processo) ?></td>
                        <td><?php echo SOSMalas_Date::dateToView($value->data_entrega_processo) ?></td>
                        <td><?php // echo $value->nome_pax_processo  ?></td>
                        <td><?php //echo $value->qtd_bagagem_processo  ?></td>
                        <td><?php echo $value->status_processo_text ?></td>
                        <td><?php //echo $value->obs_processo  ?></td>
                        <td><?php echo $value->obs_processo ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="alert alert-info">Nenhum resultado encontrado para o código informado: 
            <strong><?php echo $this->hashcod ?></strong></div>
    <?php endif; ?>
</form>