<style type="text/css">
    .form-horizontal{
        margin: 15% 0 20% 0;
    }
</style>
<form class="form-horizontal">
    <h4>
        <center>Verifique como se encontra o estado do seu pedido</center>
    </h4>
    <br>
    <br>
    <br>
    <div class="control-group">
        <label class="control-label">Buscar</label>
        <div class="controls">
            <input type="text" value="<?php echo @$this->params['hashcod'] ?>" name="hashcod" class="input-xxlarge" placeholder="Insira o codigo da sua coleta e então clique em verificar">
            <button class="btn btn-primary">Verificar</button>
        </div>
    </div>
</form>