<form action="" method="post" class="form-horizontal">
      <?php echo 'Mensagem: '.$this->texto ?>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Data de entrada: </label>
    <div class="controls">
         <?php echo $this->form->data_entrada?>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Empresa: </label>
    <div class="controls">
         <?php echo $this->form->empresa?>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Processo: </label>
    <div class="controls">
        <?php echo $this->form->processo?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Marca: </label>
    <div class="controls">
         <?php echo $this->form->marca?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Nome: </label>
    <div class="controls">
         <?php echo $this->form->nome?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Dano: </label>
    <div class="controls">
         <?php echo $this->form->dano?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Preço: </label>
    <div class="controls">
         <?php echo $this->form->preco?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Data de conclusão: </label>
    <div class="controls">
         <?php echo $this->form->data_conclusao?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Data de previsão: </label>
    <div class="controls">
         <?php echo $this->form->data_previsao?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Data de Entrega: </label>
    <div class="controls">
         <?php echo $this->form->data_entrega?>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Salvar</button>
    </div>
  </div>
</form>