<?php echo $this->element->id_entrada ?>

<div class="span5">
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->data_entrada ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->empresa_entrada ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->processo_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->marca_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->nome_entrada ?>
        </div>
    </div>
</div>
<div class="span5">
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->dano_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->preco_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->data_conclusao_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->data_previsao_entrada ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->data_entrega_entrada ?>
        </div>
    </div>
</div>
<div class="span12">
    <div class="control-group form-actions">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="reset" class="btn">Limpar</button>
        </div>
    </div>
</div>