<?php echo $this->paginacao ?>
<table class="table table-bordered table-striped table-condensed">
    <thead>
    <th>ID</th>
    <th>DPR/AHL</th>
    <th>Passageiro</th>
    <th>Quant.</th>
    <th>Serviço Realizado</th>
    <th width="85">Coleta</th>
    <th width="90">Entrega</th>
    <th>Status</th>
    <th>Obs.</th>
    <th></th>
</thead>
<tbody class="tbody">
    <?php foreach ($this->processos as $key => $processo): ?>
        <tr>
            <td><?php echo $processo->id_processo ?></td>
            <td><?php echo $processo->os_processo ?></td>
            <td><?php echo $processo->nome_pax_processo ?></td>
            <td><?php echo $processo->qtd_bagagem_processo ?></td>
            <td><?php echo $processo->servico_realizado_processo ?></td>
            <td><?php echo SOSMalas_Date::dateToView($processo->data_coleta_processo) ?></td>
            <td><?php echo SOSMalas_Date::dateToView($processo->data_entrega_processo) ?></td>
            <td><?php echo $processo->nome_status_processo ?></td>
            <td><?php echo $processo->obs_processo ?></td>
            <td>
                <div class="btn-group">
                    <?php if ($this->editar): ?>
                        <a class="btn" href="/admin/processos/editar/id/<?php echo $processo->id_processo ?>">
                            <i class="icon-edit"></i>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->delete): ?>
                        <a class="btn btn-danger" href="/admin/processos/delete/id/<?php echo $processo->id_processo ?>">
                            <i class="icon-trash icon-white"></i>
                        </a>
                    <?php endif; ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</tbody>
<input id="page" type="hidden" value="1" name="page">
</table>
<?php echo $this->paginacao;