<?php echo $this->paginacao ?>
<style>
    #btn-center{
        text-align: center;
    }
</style>
<table class="table table-bordered table-striped table-condensed" style="font-size: 12px;">
    <thead>
    <th>ID</th>
    <th>Processo</th>
    <th>Empresa</th>
    <th>Cliente</th>
    <th>Quant.</th>
    <th>Prod/Mod/Cor/Marca</th>
    <th width="180">Concerto</th>
    <th>Coleta</th>
    <th>Entrega</th>
    <th>Status</th>
    <th>Histórico</th>
    <th></th>
</thead>
<tbody class="tbody">
    <?php foreach ($this->processos as $key => $processo): ?>
        <tr>
            <td><?php echo $processo->id_processo ?></td>
            <td><?php echo $processo->cod_processo ?></td>
            <td><?php echo $processo->nome_pessoa ?></td>
            <td><?php echo $processo->nome_cliente ?></td>
            <td><?php echo $processo->quantidade ?></td>
            <td><?php echo $processo->descricao_produto ?></td>
            <td><?php echo $processo->conserto ?></td>
            <td><?php echo SOSMalas_Date::dateToView($processo->dt_coleta) ?></td>
            <td><?php echo SOSMalas_Date::dateToView($processo->dt_entrega) ?></td>
            <td><?php echo $processo->tx_status ?></td>
            <td id="btn-center">
                <button title="Histórico" class="btn"><i class="icon-list"></i></button>
            </td>
            <td>
                <div class="btn-group">
                    <?php if ($this->editar): ?>
                        <a class="btn" href="/admin/processos/editar/id/<?php echo $processo->id_processo ?>">
                            <i class="icon-edit"></i>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->delete): ?>
                        <a class="btn btn-danger" href="/admin/processos/delete/id/<?php echo $processo->id_processo ?>">
                            <i class="icon-trash icon-white"></i>
                        </a>
                    <?php endif; ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</tbody>
<input id="page" type="hidden" value="1" name="page">
</table>