<br>
Processo: <?php echo $this->cod_processo ?>
<br>
Data Coleta: <?php echo $this->dt_coleta ?>
<br>
Data Entrega: <?php echo $this->dt_entrega ?>
<br>
Cliente: <?php echo $this->nome_cliente ?>
<br>
Status: <?php echo $this->status ?>
<br>
Quantidade: <?php echo $this->quantidade ?>
<br>
Prod/Mod/Cor/Marca: <?php echo $this->descricao_produto ?>
<br>
Histórico:
<br>
<ul>
    <?php foreach ($this->historico as $value): ?>
        <li><?php echo $value->texto_historico ?>, </li>
    <?php endforeach; ?>
</ul>
<i>*Esta mensagem foi enviada para <?php echo $this->nome_contato ?> nosso correspondente na empresa <?php echo $this->nome_empresa ?> 
    se desconhece o email e/ou origem favor desconsiderar.</i>
<br>
<i>*Esta mensagem de texto gerada automaticamente pelo sistema, favor não responder por este endereço de e-mail.</i>