<div class="row-fluid">
    <div class="span5">
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->cod_processo ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->id_empresa ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->nome_cliente ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->quantidade ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->descricao_produto ?>
            </div>
        </div>
    </div>
    <div class="span5">
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->conserto ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->dt_coleta ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->dt_entrega ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->status_id ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">Observação [Gravado em Historico]</div>
            <textarea name="texto_historico" rows="3" class="span10"></textarea>
        </div>
        <?php echo $this->element->id_processo ?>
    </div>
</div>
<div class="span12">
    <div class="control-group form-actions">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="reset" class="btn">Limpar</button>
            <a class="btn btn-inverse" onclick="history.go(-1)">Cancelar</a>
        </div>
    </div>
</div>