<legend>Histórico</legend>
<table class="table table-bordered table-striped">
    <thead>
    <th>#</th>
    <th>Data Cadastro</th>
    <th>Texto Histórico</th>
    </thead>
    <tbody>
        <?php foreach($this->historico as $key=>$value): ?>
        <tr>
            <td><?php echo ($key+1) ?></td>
            <td><?php echo SOSMalas_Date::dateToView($value->dt_cadastro) ?></td>
            <td><?php echo $value->texto_historico ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    

