<script src="/angular/angular-resource.min.js"></script>
<script src="/angular/angular-route.min.js"></script>
<script type="text/javascript" src="/admin-angular/processos.js"></script>
<script type="text/javascript" src="/angular/ui-utils/modules/mask/mask.js"></script>

<div ng-app="App">
    <div ng-view></div>
    <script type="text/ng-template" id="index.html">
        <form action="" method="post" class="form-search" style="font-size: 12px;">
            <fieldset>
                <h3>Processos</h3>
                <div class="control-group">
                    <label class="control-label">
                        <strong>Buscar: </strong><input ng-model="search.input" autocomplete="off" id="auto-complete" 
                               placeholder="ID, Cliente ou Serviço" name="nome_cliente" class="search-query input-xlarge" type="text"/>
                    </label>
                    <label class="control-label">
                        <input ng-model="dtColeta" ng-controller="DatePicker" ui-mask="99-99-9999" id="appendInput" name="dt_coleta" type="text" class="date input-small">
                    </label>
                    <label class="control-label">
                        <input ng-model="dtEntrega" ui-mask="99-99-9999" name="dt_entrega" type="text" class="date input-small">
                    </label>
                    <label class="control-label">
                        <select ng-model="search.id_status" ng-options="item.tx_status for item in statusProcesso">
                            <option value="">--</option>
                        </select>
                    </label>
                    <label class="control-label">
                        <?php if($this->acl->isAllowed($this->user->tipo_acesso_id, 'admin:processos', 'combo-filter')): ?>
                            <select ng-model="search.nome_empresa">
                                <option value="">--</option>
                                <?php foreach($this->parceiros as $value): ?>
                                    <option><?=$value->nome_empresa ?></option>
                                <?php endforeach; ?>
                            </select>
                        <?php endif; ?>
                        <button ng-click="resetForm()" type="reset" class="btn">Limpar</button>
                    </label>
                    <?php if($this->acl->isAllowed($this->user->tipo_acesso_id, 'admin:processos', 'cadastrar')): ?>
                        <label class="control-label pull-right">
                            <a href="#/cadastrar" class="btn btn-primary"><i class="icon-plus-sign icon-white"></i> Cadastrar</a>
                        </label>
                    <?php endif; ?>
                </div>
            </fieldset>
        </form>
        <?php echo $this->listarTemplate ?>
    </script>
    <script type="text/ng-template" id="editar.html">
        <legend>Editar Dados</legend>
        <?= $this->formTemplate ?>
    </script>
    <script type="text/ng-template" id="cadastrar.html">
        <legend>Cadastrar</legend>
        <?= $this->formTemplate ?>
    </script>
</div>
