<div class="span5">
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->nome_pessoa; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->email_pessoa; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->tel_res_pessoa; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->tel_cel_pessoa; ?>
        </div>
    </div>
</div>
<div class="span5">
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->endereco_pessoa; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->ponto_ref_pessoa; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->tx_tipo_acesso; ?>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <?php echo $this->element->senha_pessoa; ?>
        </div>
    </div>
</div>

<?php echo $this->element->id_pessoa; ?>

<div class="span12">
    <div class="control-group form-actions">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="reset" class="btn">Limpar</button>
        </div>
    </div>
</div>