<div class="span5">
    <?php
    echo $this->element->id_pessoa;
    echo $this->element->nome_pessoa;
    echo $this->element->email_pessoa;
    echo $this->element->tel_res_pessoa;
    echo $this->element->tel_cel_pessoa;
    ?>
</div>
<div class="span5">
    <br>
    <?php
    echo $this->element->endereco_pessoa;
    echo $this->element->ponto_ref_pessoa;
    echo $this->element->senha_pessoa;
    ?>
</div>
<div class="form-actions span12">
    <button type="submit" class="btn btn-primary">Salvar</button>
    <button type="reset" class="btn">Limpar</button>
</div>
