<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Painel Administrativo</title>

        <!--<link href="/assets/css/acoordeon.css" rel="stylesheet" type="text/css" />-->
        <!--<link href="/assets/css/style.css" rel="stylesheet" type="text/css" />-->
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/jquery.ui.css" rel="stylesheet" type="text/css" />


    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <div class="navbar">
                        <a class="brand" href="/admin/index">SOS Malas - Painel Administrativo</a>
                    </div>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="#"><i class="icon-user icon-white"></i> <?php echo Zend_Auth::getInstance()->getIdentity()->nome_pessoa ?></a>
                            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/admin/pessoa/editar/id/<?php echo Zend_Auth::getInstance()->getIdentity()->id_pessoa ?>">
                                        <i class="icon-pencil"></i> 
                                        Editar Perfil
                                    </a>
                                </li>
                                <li class="divider"></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br></br>
        <br></br>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <div class="well sidebar-nav">
                        <ul class="nav nav-list">
                            <li class="active"><a>Menu</a></li>
                            <!--                            <li>
                                                            <li class="itemMenu"><a class="nav-header" href="#">Administrador</a></li>
                                                            <ul class="conteudoMenu">
                                                                <li><a href="/admin/pessoa/editar/id/<?php echo Zend_Auth::getInstance()->getIdentity()->id_pessoa ?>">Editar Perfil</a></li>
                            
                                                            </ul>
                                                        </li>-->
                            <li>
                                <li class="itemMenu"><a class="nav-header" href="#">Funcionários</a></li>
                                <ul class="conteudoMenu">
                                    <li><a href="/admin/pessoa/cadastro">Cadastrar</a></li>
                                    <li><a href="/admin/pessoa/pesquisar-pessoa">Consultar</a></li>

                                </ul>
                            </li>
                            <li>
                                <li class="itemMenu"><a class="nav-header" href="#">Processos</a></li>
                                <ul class="conteudoMenu">
                                    <li><a href="/admin/coleta/cadastro-coleta" >Cadastrar</a></li>
                                    <li><a href="/admin/coleta/pesquisar-coleta">Consultar</a></li>
                                </ul>
                            </li>
                            <li>
                                <li class="itemMenu"><a class="nav-header" href="#">Protocolo de chegada de malas</a></li>
                                <ul class="conteudoMenu">
                                    <li><a href="/admin/entrada/cadastro-entrada" >Cadastrar</a></li>
                                    <li><a href="/admin/entrada/pesquisar-entrada">Consultar</a></li>
                                </ul>
                            </li>
                            <li>
                                <li class="itemMenu"><a class="nav-header" href="/admin/coleta/consultar-status">Consultar Status</a></li>

                            </li>
                            <li>
                                <li class="itemMenu"><a class="nav-header" href="#">Peças</a></li>
                                <ul class="conteudoMenu">
                                    <li><a href="#">Cadastrar</a></li>
                                    <li><a href="#">Consultar</a></li>
                                </ul>
                            </li>



                            <li>
                                <li class="itemMenu"><a class="nav-header" href="/admin/auth/logout">Sair</a></li>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="span9">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
            <hr>
                <footer>
                    &copy; SOS Malas
                </footer>
        </div>
        <script type="text/javascript" src="/assets/js/jquery.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/js/acoordeon.js"></script>
        <script type="text/javascript" src="/assets/js/jquery.ui.js"></script>
        <script type="text/javascript" src="/assets/js/dropdown-bootstrap.js"></script>
        <script type="text/javascript" src="/assets/js/confirm-action.js"></script>
    </body>

</html>
