<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="/assets/css/bootstrap.css">
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/less/datepicker.less">
        <link rel="stylesheet" href="/assets/css/datepicker.css">
        <link rel="stylesheet" href="/assets/css/main.css">
        <link rel="stylesheet" href="/assets/css/icons-desktop.css">
        <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
        <script src="/angular/angular.min.js"></script>
        <script type="text/javascript" src="/assets/js/main.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/js/dropdown-bootstrap.js"></script>
        <script type="text/javascript" src="/assets/js/datepicker/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="/assets/js/datepicker/locales/bootstrap-datepicker.br.js"></script>
        <script type="text/javascript" src="/assets/js/jquery.maskMoney.js"></script>
        <script type="text/javascript" src="/assets/js/masks.js"></script>
        <script type="text/javascript" src="/assets/js/utils.js"></script>
        <title><?php echo Zend_Registry::get('layoutTitle'); ?></title>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <?php echo $this->render('menu.phtml') ?>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="container">
            <div class="row">
                <section class="span12" style="font-size: 13px;">
                    <?php echo $this->render('flashMessenger.phtml'); ?>
                    <?php echo $this->layout()->content ?>
                </section>
            </div>
            <hr>
            <footer>
                <div class="hide">
                    <?php Zend_Debug::dump(Zend_Registry::get('acl')); ?>
                </div>
                &copy; SOS Malas
            </footer>
        </div>
        <div id="overlay"></div>
    </body>
</html>
