<?php
$user = Zend_Auth::getInstance()->getIdentity();
$session = new Zend_Session_Namespace();
?>
<div class="container">
    <!--                    <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>-->
    <a href="/admin/index" class="brand" title="SOS Malas">SOS Malas</a>
    <div class="nav-collapse collapse">
        <ul class="nav">
            <li class="active"><a href="/admin/index">Área de Trabalho</a></li>
            <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:pessoa')): ?>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <strong>Parceiro/Funcionário</strong>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Menu de Opções</li>
                        <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:pessoa', 'cadastro')): ?>
                            <li><a href="/admin/pessoa/cadastro"><i class="icon-plus"></i> Cadastrar</a></li>
                        <?php endif ?>
                        <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:pessoa', 'pesquisar-pessoa')): ?>
                            <li><a href="/admin/pessoa/index"><i class="icon-eye-open"></i> Visualizar</a></li>
                        <?php endif ?>
                    </ul>
                </li>
            <?php endif ?>
            <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:processos', 'pesquisar')): ?>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <strong>Processos</strong>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Menu de Opções</li>
                        <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:processos', 'cadastrar')): ?>
                            <li><a href="/admin/processos/cadastrar"><i class="icon-plus"></i> Cadastrar</a></li>
                        <?php endif ?>
                        <?php if ($session->registerRoleResource->isAllowed($user->tx_tipo_acesso, 'admin:processos', 'pesquisar')): ?>
                            <li><a href="/admin/processos/pesquisar"><i class="icon-search"></i> Consultar</a></li>
                        <?php endif ?>
                    </ul>
                </li>
            <?php endif ?>
        </ul>
        <a class="btn btn-danger btn-small pull-right" href="/admin/auth/logout">Sair</a>
        <div class="btn btn-info btn-small pull-right"><?php echo Zend_Auth::getInstance()->getIdentity()->nome_pessoa ?></div>
    </div>
</div>