<div class="container">
    <!--                    <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>-->
    <a href="/admin/index" class="brand" title="SOS Malas">SOS Malas</a>
    <div class="nav-collapse collapse">
        <ul class="nav">
            <li class="active"><a href="/admin/index">Área de Trabalho</a></li>
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <strong>Pessoas</strong>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-header">Menu de Usuários</li>
                    <li><a href="/admin/pessoa/cadastro"><i class="icon-plus"></i> Cadastrar Pessoa</a></li>
                    <li><a href="/admin/pessoa/pesquisar-pessoa"><i class="icon-search"></i> Consultar Pessoa</a></li>
                </ul>
            </li>
<!--            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <strong>Coletas</strong>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-header">Menu de Coletas</li>
                    <li><a href="/admin/coleta/cadastro-coleta" ><i class="icon-plus"></i> Cadastrar Coleta</a></li>
                    <li><a href="/admin/coleta/pesquisar-coleta"><i class="icon-search"></i> Consultar Coleta</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <strong>Entradas</strong>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-header">Protocolo de chegada de malas</li>
                    <li><a href="/admin/entrada/cadastro"><i class="icon-plus"></i> Cadastrar</a></li>
                    <li><a href="/admin/entrada/pesquisar-entrada"><i class="icon-search"></i> Consultar</a></li>
                </ul>
            </li>-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <strong>Processos</strong>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-header">Processos</li>
                    <li><a href="/admin/processos/cadastrar"><i class="icon-plus"></i> Cadastrar</a></li>
                    <li><a href="/admin/processos/pesquisar"><i class="icon-search"></i> Consultar</a></li>
                </ul>
            </li>
        </ul>
        <a class="btn btn-danger btn-small pull-right" href="/admin/auth/logout">Sair</a>
        <div class="btn btn-info btn-small pull-right"><?php echo Zend_Auth::getInstance()->getIdentity()->nome_pessoa ?></div>
    </div>
</div>